export const FECTH_DETAIL_MOVIE_REQUEST = "/chi-tiet-phim/FECTH_DETAIL_MOVIE_REQUEST";
export const FECTH_DETAIL_MOVIE_SUCCESS = "/chi-tiet-phim/FECTH_DETAIL_MOVIE_SUCCESS";
export const FECTH_DETAIL_MOVIE_FAILED = "/chi-tiet-phim/FECTH_DETAIL_MOVIE_FAILED";
