export const FECTH_LIST_USER_REQUEST = "/user-manager/FETCH_LIST_USER_REQUEST";
export const FECTH_LIST_USER_SUCCESS = "/user-manager/FETCH_LIST_USER_SUCCESS";
export const FECTH_LIST_USER_FAILED = "/user-manager/FETCH_LIST_USER_FAILED";

export const FECTH_DETAIL_USER_SUCCESS = "FECTH_DETAIL_USER_SUCCESS";
export const FECTH_DETAIL_USER_FAILED = "FECTH_DETAIL_USER_FAILED";



