export const FECTH_MOVIE_COMING_SOON_REQUEST = "FECTH_MOVIE_COMING_SOON_REQUEST";
export const FECTH_MOVIE_COMING_SOON_SUCCESS = "FECTH_MOVIE_COMING_SOON_SUCCESS";
export const FECTH_MOVIE_COMING_SOON_FAILED = "FECTH_MOVIE_COMING_SOON_FAILED";
