export const FECTH_SHOWTIME_DETAIL_REQUEST = "/chi-tiet-phim/FECTH_SHOWTIME_DETAIL_REQUEST"
export const FECTH_SHOWTIME_DETAIL_SUCCESS = "/chi-tiet-phim/FECTH_SHOWTIME_DETAIL_SUCCESS"
export const FECTH_SHOWTIME_DETAIL_FAILED = "/chi-tiet-phim/FECTH_SHOWTIME_DETAIL_FAILED"